---
- name: Upgrade Debian and Ubuntu machines in homelab
  hosts: lab_servers
  become: yes
  gather_facts: yes
  
  vars:
    # Set to yes if you want to reboot after upgrades (if required)
    auto_reboot: no
    # Maximum time to wait for reboot (in seconds)
    reboot_timeout: 300

  tasks:
    - name: Check if the system is Debian or Ubuntu
      fail:
        msg: "This playbook only supports Debian and Ubuntu systems"
      when: ansible_os_family != "Debian"

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: cache_update

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display upgrade results
      debug:
        msg: |
          Packages upgraded: {{ upgrade_result.changed }}
          Reboot required: {{ reboot_required.stat.exists }}

    - name: Reboot system if required and auto_reboot is enabled
      reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        msg: "Rebooting after package upgrades"
      when: 
        - reboot_required.stat.exists
        - auto_reboot | bool
      register: reboot_result

    - name: Wait for system to come back online after reboot
      wait_for_connection:
        delay: 30
        timeout: "{{ reboot_timeout }}"
      when: reboot_result is defined and reboot_result.changed

    - name: Clean package cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Show final status
      debug:
        msg: |
          System upgrade completed successfully!
          {% if reboot_required.stat.exists and not auto_reboot %}
          WARNING: A reboot is required to complete the upgrade.
          {% endif %}
